### ISSUE TITLE
On hovering the navbar items the color should be yellow.

### ISSUE THREAD

**Issue by VANSHAJB10** [VANSHAJB10/Agro-modern-UI#4]

**Comment by Bhavya-Chawla** [comment]
Your project looks innovative and interesting. I would really like to work on it. Can you please assign me this issue?

**Comment by HarshSingh21** [comment]
done .

**Comment by VANSHAJB10** [comment]
> Your project looks innovative and interesting. I would really like to work on it. Can you please assign me this issue?

It's been already solved and merged.
You can work on some other issue
